### ISSUE TITLE
Wrong item type/quality in trade

### ISSUE THREAD

**Issue by Sharingisnotillegal** [TastyLollipop/OpenWorld#17]
1.2.3 server, no mods except bare minimum (core, hugslib, openworld, harmony)
Ingame: Secrecy
Sadly log tool seems to have broken for me.

Sent Guinea pig parka Normal, Lightleather parka Masterwork, Pigskin Parka masterwork.

Friend received Cloth Parka normal x3

**Comment by ghost** [comment]
Hello there! Sorry this took so long, issue got lost in time.

Yeah, currently qualities don't actually get transferred between saves, Rimworld just doesn't want to colaborate with the code and just decides to spawn a normal preset instead of taking the parameters the server sends. Will totally try to fix it up in the near future
