### ISSUE TITLE
bug error using other version

### ISSUE THREAD

**Issue by Marcus89uk** [TastyLollipop/OpenWorld#22]
Hi I am having a problem joining my own server. it keeps saying on the console that I am using other version but i am using the correct version. i have rimworld on steam and everything is up to date.

**Comment by tenletters10** [comment]
Running into the same issues as well. Have verified I am using the most current copy of the Open World both on the client and on the server.

**Comment by ghost** [comment]
There is no actual problem with latest version not working. If the server is kicking out clients for having other versions then that's exactly what's happening. If the issue persists, force the update of all the files using the file verification system of Steam.

Library > Rimworld > Right Click > Properties > Verify Integrity Of Files.

A lot of people have already had this problem, it's all just solved by forcing the update since they were just running outdated versions and Steam wouldn't update automatically.

**Comment by tenletters10** [comment]
@TastyLollipop 

Wanted to let you know that did the trick. Thanks for the help with that. 

I saw how the files got updated for the mod folder for Open World when that action was performed at: "C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2768146099\"

**Comment by Marcus89uk** [comment]
Thank you for the help
