### ISSUE TITLE
Open the Source Code

### ISSUE THREAD

**Issue by DylanTN** [TastyLollipop/OpenWorld#31]
If you are only one dev and are not trying to make money off of this, you should really open up the code so the community can help contribute. I was hoping to be able to dabble with the code and make improvements where possible, but how you are doing this that simply cannot happen. I understand not wanting to have someone rip the code from you and claim it as your own, in that case just make sure you have the right license attached to the repository.

**Comment by bchilcott** [comment]
Absolutely this - ~~if you're including the project source in the GitHub releases anyway it would be good to add the code to this repo~~.

**Comment by ghost** [comment]
Hello there! Thanks for sharing your feedback of the project @DylanTN.

As it has been said multiple times during the development, the mod source code won't be released to the public for now. It's a decision that was decided since the begining of the project and will stay put until it becomes too hard for one person to manage or I just change my opinion. There are various reasons for it to remain this way for now.

On a side note to @bchilcott comment, the "Source" is being shared with each release because Github does it automatically and I haven't been able to find a way of disabling it. Perhaps I'm missing something on that regard?

**Comment by bchilcott** [comment]
Ah sorry, I thought you had chosen to share the actual project source. Didn't realise GitHub includes the repo content automatically. I don't know of a way to disable that sadly.

I can't say I agree with your decision to keep this project closed - sharing the source code doesn't mean that you have to accept any contributions from other people; you could completely ignore all PRs if you wanted to. It just gives the community a bit of reassurance that the project won't just die one day with no hope of reviving it. I don't really see any drawbacks. I hope you reconsider your position on that in the near future.

Edit: As @DylanTN mentioned above, not being credited for your work is of course a potential issue, but generally keeping mods for any game closed for this reason alone is more damaging for the modding community. I'd be interested to know the reasoning behind your decision.

**Comment by valeredev** [comment]
Actually I'm one of those who 'd like to contribute to the project.
I think the project is awsome and could be one of the best things that can happen to rimworld.
